...
Teşhis Raporu Başlatılıyor...
[DURUM]: # "GCP Sırrı: OK (Başarıyla okundu)"
[DURUM]: # "Green API Token: OK (Başarıyla okundu)"
[DURUM]: # "WhatsApp Grup ID: OK (Değer: 905xxxxxxxxx)"
[DURUM]: # "Google Sheets Bağlantısı: OK"
[DURUM]: # "'Personel' Sayfası: OK (Başarıyla bulundu)"
[HATA]: # "Personel Bulunamadı: 'Tuğçe Hanım' ismi, 'Personel' sayfasında bulunamadı. Lütfen isimlerin tam olarak eşleştiğini kontrol edin."
...
